language: node_js
node_js: "9"
cache:
  directories:
    - node_modules
install:
  - rm -rf npm-shrinkwrap.json
  - npm install
  - npm prune
  - npm dedupe
script:
  - npm run test
  - npm run build
after_success:
  - npm run deploy
  - npm run report
